# Generated by Django 3.2.9 on 2022-05-23 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='value',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
