# Generated by Django 3.2.9 on 2022-05-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0003_remove_wishlist_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='image',
            field=models.ImageField(default='pix.jpg', upload_to='faculty'),
        ),
    ]
