# Generated by Django 3.2.9 on 2022-05-25 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0004_wishlist_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist',
            name='depart',
        ),
    ]
