# Generated by Django 3.2.9 on 2022-05-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolapp', '0005_remove_wishlist_depart'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='amount',
            field=models.IntegerField(null=True),
        ),
    ]
